language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - pip install codecov
    - pip install -r requirements.txt
    - pip install -e .

script:
    - make test

after_success:
    - codecov

notifications:
    email: false
